# Redis Cache Server for NASA ISS Tracker
# This sets up a simple Express server with Redis caching for chatbot responses

version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: iss-tracker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: iss-tracker-redis-ui
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

# To start Redis:
# docker-compose up -d

# Open http://localhost:8081 in browser